export type Language = 'en' | 'de';
export const languages: Language[] = ['en', 'de'];
export const projectSlugs = ['swagri', 'creonix', 'goalcompass', 'jobcompass'] as const;
export const visionSlugs = ['intelligence-attractor', 'origin-attenuation', 'relational-narrowing'] as const;

const enProjects = {
  swagri: {
    state: 'Concept · R&D', tone: 'acid', size: 'featured', title: 'Swagri', mark: 'SW', eyebrow: 'Project / distributed R&D',
    description: 'Adaptive Swarm Grid for efficient distributed execution across heterogeneous devices.',
    facts: [['Role', 'Concept author'], ['Status', 'R&D'], ['Domain', 'Edge · P2P'], ['Direction', 'Rust']],
    signal: ['Heterogeneous devices', 'Distributed execution', 'Adaptive coordination'],
    sections: [
      { index: '01', kicker: 'Idea', title: 'Computing as an adaptive network, not a single centre.', body: 'Swagri explores how devices with different performance, memory, energy constraints and connection quality can become one shared execution environment.' },
      { index: '02', kicker: 'Focus', title: 'Assign work according to the real capacity of each node.', body: 'The central questions are scheduling, P2P communication, fault tolerance, throughput and avoiding unnecessary data movement. The grid must adapt as nodes join, leave or change state.' },
      { index: '03', kicker: 'Status', title: 'A priority research direction.', body: 'The project is currently shaping its architecture and performance criteria. This page presents the direction without exposing the private repository before a demonstrable slice is ready.' },
    ], links: [], materialsTitle: 'Private development', materialsNote: 'Code and technical materials are not public yet.'
  },
  creonix: {
    state: 'Prototype · private', tone: 'blue', size: 'featured', title: 'Creonix', mark: 'CR', eyebrow: 'Project / swarm intelligence',
    description: 'A decentralised swarm AI prototype with distributed memory, trust scores and rewards for useful work.',
    facts: [['Role', 'Author & developer'], ['Status', 'Prototype'], ['Language', 'Python'], ['Architecture', 'P2P · FAISS']],
    signal: ['Distributed memory', 'Trust score and decay', 'Proof of Useful Work'],
    sections: [
      { index: '01', kicker: 'Idea', title: 'A swarm that computes and remembers.', body: 'Creonix models a network without a single centre. Each node can hold a shard of shared knowledge, exchange fragments and participate in answering queries.' },
      { index: '02', kicker: 'Mechanism', title: 'Trust, forgetting and knowledge reconstruction.', body: 'Every knowledge item has a trust score. Unused information may decay, be archived or reduced to a lightweight representation, then reconstructed locally, through peer nodes or from an external source when needed again.' },
      { index: '03', kicker: 'Incentive', title: 'Reward useful participation rather than idle energy use.', body: 'Proof of Useful Work measures contributions to query resolution, inference, knowledge transfer and memory. A related ephemeral participation unit explores value tied to a node’s active presence.' },
    ], links: [], materialsTitle: 'Private prototype', materialsNote: 'The concept is public; the source code remains private at this stage.'
  },
  goalcompass: {
    state: 'Active · 0.4.1', tone: 'paper', size: 'compact', title: 'GoalCompass', mark: 'GC', eyebrow: 'Project / personal effectiveness',
    description: 'A local-first personal effectiveness assistant that connects daily activity with goals and working modes.',
    facts: [['Role', 'Author & developer'], ['Version', '0.4.1'], ['Platform', 'Windows'], ['Language', 'Python']],
    signal: ['Local activity database', 'Goals and rules', 'AI without a required API'],
    sections: [
      { index: '01', kicker: 'Problem', title: 'Goals often live separately from what a person does today.', body: 'Time trackers count minutes and task lists count completed items. GoalCompass adds context: which goal an activity supports and whether it matches the current working mode.' },
      { index: '02', kicker: 'Approach', title: 'A local control centre with a lightweight overlay.', body: 'The app combines activity rules, goal profiles, progress, schedules, statistics and a small overlay. The manual workflow is primary; AI-assisted configuration works through copy and paste without requiring an API key.' },
      { index: '03', kicker: 'Principle', title: 'Personal history stays on the user’s computer.', body: 'Profiles, settings, activity and proposal history are stored locally. Updates preserve personal data and require confirmation before installation.' },
    ], links: [], materialsTitle: 'Private beta', materialsNote: 'The project is active, but public downloads are not available yet.'
  },
  jobcompass: {
    state: 'Active · v0.11.2', tone: 'paper', size: 'compact', title: 'JobCompass', mark: 'JC', eyebrow: 'Project / local product',
    description: 'A local Windows app that finds vacancies, explains relevance and keeps the application workflow organised.',
    facts: [['Role', 'Author & developer'], ['Version', '0.11.2'], ['Platform', 'Windows 10/11'], ['Technology', 'Python · Tkinter']],
    signal: ['Local storage', 'Explainable score 0—100%', 'Ukrainian · English · German'],
    sections: [
      { index: '01', kicker: 'Problem', title: 'A job search fragments into dozens of tabs.', body: 'Vacancies arrive from different sources, relevance scores are often opaque and application history is easy to lose. JobCompass brings search, CV comparison, favourites, statuses and application material into one local workspace.' },
      { index: '02', kicker: 'Approach', title: 'Useful automation without giving up control.', body: 'The app reads JSON, TXT, DOCX and PDF CVs, searches public sources and career sites, normalises results and shows an explainable match score. The person always confirms the final application.' },
      { index: '03', kicker: 'Result', title: 'A packaged Windows application, not only a prototype.', body: 'Installer and portable builds are available alongside multiple candidate profiles, guest mode, scheduled daily search, status history and update verification.' },
    ], links: [
      { label: 'Download Setup', href: 'https://github.com/vitalii87/JobCompass/releases/download/v0.11.2/JobCompass-0.11.2-Setup.exe', primary: true },
      { label: 'Portable ZIP', href: 'https://github.com/vitalii87/JobCompass/releases/download/v0.11.2/JobCompass-0.11.2-Portable.zip' },
      { label: 'GitHub', href: 'https://github.com/vitalii87/JobCompass' },
    ], materialsTitle: 'Open the project', materialsNote: ''
  },
};

const deProjects = {
  swagri: { ...enProjects.swagri, state: 'Konzept · F&E', eyebrow: 'Projekt / verteilte F&E', description: 'Adaptive Swarm Grid für effiziente verteilte Ausführung auf heterogenen Geräten.', facts: [['Rolle', 'Konzeptautor'], ['Status', 'F&E'], ['Bereich', 'Edge · P2P'], ['Richtung', 'Rust']], signal: ['Heterogene Geräte', 'Verteilte Ausführung', 'Adaptive Koordination'], sections: [
    { index: '01', kicker: 'Idee', title: 'Rechnen als adaptives Netz statt als einzelnes Zentrum.', body: 'Swagri untersucht, wie Geräte mit unterschiedlicher Leistung, Speicherkapazität, Energiegrenze und Verbindungsqualität zu einer gemeinsamen Ausführungsumgebung werden können.' },
    { index: '02', kicker: 'Fokus', title: 'Arbeit nach den realen Fähigkeiten jedes Knotens verteilen.', body: 'Im Mittelpunkt stehen Scheduling, P2P-Kommunikation, Fehlertoleranz, Durchsatz und die Vermeidung unnötiger Datenbewegungen. Das Grid passt sich an, wenn Knoten kommen, gehen oder ihren Zustand ändern.' },
    { index: '03', kicker: 'Status', title: 'Ein priorisierter Forschungsbereich.', body: 'Derzeit entstehen Architektur und Leistungskriterien. Die Seite zeigt die Richtung, ohne das private Repository vor einem belastbaren Demonstrator offenzulegen.' },
  ], materialsTitle: 'Private Entwicklung', materialsNote: 'Code und technische Unterlagen sind noch nicht öffentlich.' },
  creonix: { ...enProjects.creonix, state: 'Prototyp · privat', eyebrow: 'Projekt / Schwarmintelligenz', description: 'Dezentraler Schwarm-KI-Prototyp mit verteiltem Gedächtnis, Vertrauenswerten und Belohnung nützlicher Arbeit.', facts: [['Rolle', 'Autor & Entwickler'], ['Status', 'Prototyp'], ['Sprache', 'Python'], ['Architektur', 'P2P · FAISS']], signal: ['Verteiltes Gedächtnis', 'Trust Score und Verfall', 'Proof of Useful Work'], sections: [
    { index: '01', kicker: 'Idee', title: 'Ein Schwarm, der rechnet und sich erinnert.', body: 'Creonix modelliert ein Netz ohne einziges Zentrum. Jeder Knoten kann einen Teil des gemeinsamen Wissens speichern, Fragmente austauschen und an Antworten mitwirken.' },
    { index: '02', kicker: 'Mechanik', title: 'Vertrauen, Vergessen und Rekonstruktion von Wissen.', body: 'Jeder Wissenseintrag besitzt einen Trust Score. Ungenutzte Information kann verfallen, archiviert oder reduziert und bei Bedarf lokal, über andere Knoten oder externe Quellen rekonstruiert werden.' },
    { index: '03', kicker: 'Anreiz', title: 'Nützliche Beteiligung statt passiven Energieverbrauch belohnen.', body: 'Proof of Useful Work bewertet Beiträge zu Anfragebearbeitung, Inferenz, Wissenstransfer und Gedächtnis. Eine vergängliche Beteiligungseinheit bindet Wert an aktive Präsenz.' },
  ], materialsTitle: 'Privater Prototyp', materialsNote: 'Das Konzept ist öffentlich; der Quellcode bleibt vorerst privat.' },
  goalcompass: { ...enProjects.goalcompass, state: 'Aktiv · 0.4.1', eyebrow: 'Projekt / persönliche Effektivität', description: 'Local-first-Assistent, der tägliche Aktivität mit Zielen und Arbeitsmodi verbindet.', facts: [['Rolle', 'Autor & Entwickler'], ['Version', '0.4.1'], ['Plattform', 'Windows'], ['Sprache', 'Python']], signal: ['Lokale Aktivitätsdatenbank', 'Ziele und Regeln', 'KI ohne API-Pflicht'], sections: [
    { index: '01', kicker: 'Problem', title: 'Ziele sind oft von dem getrennt, was heute passiert.', body: 'Zeiterfassung zählt Minuten, Aufgabenlisten zählen Häkchen. GoalCompass ergänzt den Kontext: Welches Ziel unterstützt eine Aktivität und passt sie zum aktuellen Arbeitsmodus?' },
    { index: '02', kicker: 'Ansatz', title: 'Lokales Kontrollzentrum mit leichtem Overlay.', body: 'Die Anwendung verbindet Aktivitätsregeln, Zielprofile, Fortschritt, Zeitpläne, Statistiken und ein kleines Overlay. Der manuelle Ablauf bleibt zentral; KI-Konfiguration funktioniert per Copy-and-paste ohne API-Schlüssel.' },
    { index: '03', kicker: 'Prinzip', title: 'Persönliche Historie bleibt auf dem eigenen Rechner.', body: 'Profile, Einstellungen, Aktivitäten und Vorschläge werden lokal gespeichert. Updates bewahren persönliche Daten und benötigen eine Bestätigung.' },
  ], materialsTitle: 'Private Beta', materialsNote: 'Das Projekt wird aktiv entwickelt; ein öffentlicher Download ist noch nicht verfügbar.' },
  jobcompass: { ...enProjects.jobcompass, state: 'Aktiv · v0.11.2', eyebrow: 'Projekt / lokales Produkt', description: 'Lokale Windows-App, die Stellen findet, Relevanz erklärt und Bewerbungen strukturiert.', facts: [['Rolle', 'Autor & Entwickler'], ['Version', '0.11.2'], ['Plattform', 'Windows 10/11'], ['Technologie', 'Python · Tkinter']], signal: ['Lokale Speicherung', 'Erklärbarer Score 0—100%', 'Ukrainisch · Englisch · Deutsch'], sections: [
    { index: '01', kicker: 'Problem', title: 'Die Jobsuche zerfällt in Dutzende Tabs.', body: 'Stellen kommen aus verschiedenen Quellen, Relevanzwerte sind oft undurchsichtig und Bewerbungsverläufe gehen verloren. JobCompass bündelt Suche, Lebenslaufabgleich, Favoriten, Status und Unterlagen lokal.' },
    { index: '02', kicker: 'Ansatz', title: 'Nützliche Automatisierung ohne Kontrollverlust.', body: 'Die App liest JSON-, TXT-, DOCX- und PDF-Lebensläufe, durchsucht öffentliche Quellen, normalisiert Ergebnisse und zeigt einen erklärbaren Match Score. Die endgültige Bewerbung bestätigt immer der Mensch.' },
    { index: '03', kicker: 'Ergebnis', title: 'Eine fertige Windows-Anwendung, nicht nur ein Prototyp.', body: 'Installer und Portable-Version stehen neben mehreren Kandidatenprofilen, Gastmodus, täglicher Suche, Statushistorie und Updateprüfung bereit.' },
  ], links: [
    { label: 'Setup herunterladen', href: 'https://github.com/vitalii87/JobCompass/releases/download/v0.11.2/JobCompass-0.11.2-Setup.exe', primary: true },
    { label: 'Portable ZIP', href: 'https://github.com/vitalii87/JobCompass/releases/download/v0.11.2/JobCompass-0.11.2-Portable.zip' },
    { label: 'GitHub', href: 'https://github.com/vitalii87/JobCompass' },
  ], materialsTitle: 'Projekt öffnen', materialsNote: '' },
};

const enVisions = {
  'intelligence-attractor': { category: 'Conceptual preprint · v0.1 · 2026', title: 'The Intelligence Attractor Hypothesis', description: 'Independent convergence, origin attenuation and architectural optimisation under shared reality constraints.', intro: 'Could independently formed intelligent systems lose functionally consequential differences as they approach the best attainable performance under the same task, objective, context and resource constraints?', outline: ['Foundational claim', 'Weak and Strong IAH', 'Architecture', 'Collective organisation'], sections: [
    { title: 'Convergence under shared constraints', paragraphs: ['IAH proposes that independent optimisation near a shared frontier progressively replaces origin-contingent functional variation with structure determined by the task and its binding constraints.', 'Early in optimisation, many strategies, algorithms and architectures may remain competitive. Near the frontier, costly forms of organisation are eliminated and independent lineages may reconstruct similar functional principles.'], quote: 'There may be far more ways to remain inefficient than ways to remain competitive near the best attainable performance.' },
    { title: 'Weak and Strong IAH', paragraphs: ['Weak IAH makes two separate predictions: functional diversity decreases in a prespecified near-frontier regime, and controlled differences in origin have progressively less influence on the measured functional properties.', 'Strong IAH goes further. Within a specified domain and at a defined descriptive level, all sufficiently near-optimal systems approach one common limiting class of functional equivalence. Declining mean similarity alone is not enough to establish this stronger claim.'] },
    { title: 'Architecture can enter the search space', paragraphs: ['If memory, computation, communication, control or the mechanism of optimisation itself can be modified and materially affects performance, these properties become part of the optimisation problem.', 'IAH therefore distinguishes outcome, behaviour, strategy, representation, algorithm, architecture and resource use. Convergence at one level does not prove convergence at another.'] },
    { title: 'System boundaries may also be mutable', paragraphs: ['When agents can share memory, delegate computation, specialise or form joint control loops, the admissible space includes forms of collective organisation.', 'Optimisation may favour integration, autonomy or cooperation without merger depending on communication, reliability and restructuring costs. The hypothesis must compare independently formed collectives at the level of their overall organisation.'] },
  ], source: 'https://doi.org/10.5281/zenodo.22556018' },
  'origin-attenuation': { category: 'IAH · Appendix A · v0.1', title: 'Origin Attenuation', description: 'A testable claim that historically contingent differences should exert less influence on functional properties near a shared frontier.', intro: 'When independently optimised systems approach the same performance frontier, does their origin still determine the parts of their organisation that matter?', outline: ['Origin variables', 'Measurement', 'Shared inheritance', 'Negative results'], sections: [
    { title: 'Origin is a controlled variable', paragraphs: ['An origin vector may include initial architecture, training data, instructions, tools, prior context, development history and random seed. Earlier site drafts called this idea “Salt Sensitivity”; preprint v0.1 replaces that informal label with explicit origin variables and the testable claim of Origin Attenuation.', 'Current environment, objective, resources, future randomness and measurement error must be described separately. If architecture is fixed, the result concerns one architectural family; if it can be redesigned, attenuation of its initial influence becomes testable.'], quote: 'Origin Attenuation predicts a declining influence of historical contingency, not the disappearance of every difference.' },
    { title: 'Measure effects, not surface resemblance', paragraphs: ['A study must define in advance how interventions on origin affect selected functional properties. The primary measure can compare distributions under different origin interventions, but it must correspond to the stated prediction.', 'Absolute effect magnitude and its share of total variance are different quantities. Selection only among systems that reached high performance can also manufacture apparent convergence, so complete trajectories and failed lineages matter.'] },
    { title: 'Separate reconstruction from inheritance', paragraphs: ['Similarity may come from copying a ready-made solution, sharing model ancestry or independently discovering the same principle through interaction with the environment.', 'The strongest designs vary starting systems and developmental histories while measuring common implementations, data and observations as possible causes of similarity.'] },
    { title: 'Persistent origin effects are evidence', paragraphs: ['If controlled origin differences continue to produce separated functional outcomes near the frontier, the Origin Attenuation claim is weakened for that domain, intervention and descriptive level.', 'This is an empirical result, not a failed experiment. Support for origin attenuation must also be reported separately from support for functional narrowing.'] },
  ], source: 'https://doi.org/10.5281/zenodo.22556018' },
  'relational-narrowing': { category: 'IAH · Appendix C · v0.1', title: 'Relational Narrowing & Strong Functional Uniqueness', description: 'How more precise causal context can distinguish alternatives and how a unique limiting functional class could be tested.', intro: 'Equal scores do not necessarily mean equal systems: latency, energy, memory, reliability and other prespecified consequences may reveal functional differences.', outline: ['Optimality as relation', 'Functional equivalence', 'Near-optimal geometry', 'Counterexamples'], sections: [
    { title: 'Optimality is relational', paragraphs: ['A system is optimal only relative to a defined context and objective. Adding a more accurate measurement of an already relevant consequence may separate alternatives that previously appeared tied.', 'If a refinement changes what is valued rather than measuring the original criterion more precisely, it creates a new objective and domain.'], quote: 'More complete context can narrow accidental ties, but it does not guarantee uniqueness.' },
    { title: 'Scores are not functional equivalence', paragraphs: ['Functional equivalence must be defined through prespecified properties, invariances and thresholds rather than final score alone. Different encodings may be equivalent, while systems with the same score may fail differently under intervention.', 'The descriptive level matters: outcomes may converge while algorithms or architectures remain distinct.'] },
    { title: 'The geometry near the frontier', paragraphs: ['Strong IAH requires the functional diameter of the entire near-optimal set to approach zero and a common limiting class to exist in the stated space.', 'A unique exact optimum does not by itself prove that every sequence of near-optimal systems converges to it. Conversely, a non-attained supremum may still permit concentration near a limit.'] },
    { title: 'Multiplicity can falsify the strong claim', paragraphs: ['Symmetries, plateaus, specialisation, indifference under the objective or unresolved trade-offs may preserve several equally optimal functional classes.', 'In a finite or exhaustively explored space, two globally optimal systems with nonzero functional distance refute unique optimal functional class for that domain. An arbitrary preference added after observing the tie cannot remove the counterexample.'] },
  ], source: 'https://doi.org/10.5281/zenodo.22556018' },
};

const deVisions = {
  'intelligence-attractor': { ...enVisions['intelligence-attractor'], category: 'Konzeptioneller Preprint · v0.1 · 2026', title: 'Die Hypothese des Intelligenz-Attraktors', description: 'Unabhängige Konvergenz, Abschwächung des Ursprungseinflusses und Architekturoptimierung unter gemeinsamen Realitätsbedingungen.', intro: 'Verlieren unabhängig entstandene intelligente Systeme funktional bedeutsame Unterschiede, wenn sie sich unter derselben Aufgabe, Zielsetzung, demselben Kontext und denselben Ressourcen der bestmöglichen Leistung nähern?', outline: ['Grundthese', 'Weak und Strong IAH', 'Architektur', 'Kollektive Organisation'], sections: [
    { title: 'Konvergenz unter gemeinsamen Bedingungen', paragraphs: ['IAH nimmt an, dass unabhängige Optimierung nahe einer gemeinsamen Leistungsgrenze ursprungsbedingte funktionale Variation zunehmend durch Strukturen ersetzt, die von der Aufgabe und ihren bindenden Einschränkungen bestimmt werden.', 'Zu Beginn können viele Strategien, Algorithmen und Architekturen konkurrenzfähig sein. Nahe der Grenze werden kostspielige Organisationsformen ausgesiebt; unabhängige Entwicklungslinien können ähnliche funktionale Prinzipien rekonstruieren.'], quote: 'Es könnte weit mehr Möglichkeiten geben, ineffizient zu bleiben, als nahe der bestmöglichen Leistung konkurrenzfähig zu sein.' },
    { title: 'Weak und Strong IAH', paragraphs: ['Weak IAH macht zwei getrennte Vorhersagen: Die funktionale Vielfalt nimmt in einem vorab festgelegten grenznahen Bereich ab, und kontrollierte Ursprungsunterschiede beeinflussen die gemessenen funktionalen Eigenschaften immer weniger.', 'Strong IAH behauptet mehr: In einer spezifizierten Domäne und auf einer definierten Beschreibungsebene nähern sich alle hinreichend optimalen Systeme einer gemeinsamen Grenzklasse funktionaler Äquivalenz. Sinkende mittlere Distanz allein belegt diese starke Aussage nicht.'] },
    { title: 'Architektur kann Teil des Suchraums werden', paragraphs: ['Wenn Gedächtnis, Berechnung, Kommunikation, Kontrolle oder der Optimierungsmechanismus selbst veränderbar sind und die Leistung beeinflussen, werden sie Teil des Optimierungsproblems.', 'IAH unterscheidet daher Ergebnis, Verhalten, Strategie, Repräsentation, Algorithmus, Architektur und Ressourcennutzung. Konvergenz auf einer Ebene beweist sie nicht auf einer anderen.'] },
    { title: 'Auch Systemgrenzen können veränderlich sein', paragraphs: ['Wenn Agenten Speicher teilen, Berechnung delegieren, sich spezialisieren oder gemeinsame Kontrollkreise bilden können, umfasst der zulässige Raum verschiedene kollektive Organisationsformen.', 'Je nach Kommunikations-, Zuverlässigkeits- und Umbaukosten kann Optimierung Integration, Autonomie oder Kooperation ohne Verschmelzung begünstigen. Verglichen werden müssen unabhängig entstandene Kollektive als Gesamtorganisation.'] },
  ] },
  'origin-attenuation': { ...enVisions['origin-attenuation'], category: 'IAH · Anhang A · v0.1', title: 'Abschwächung des Ursprungseinflusses', description: 'Die prüfbare These, dass historisch bedingte Unterschiede nahe einer gemeinsamen Leistungsgrenze weniger Einfluss auf funktionale Eigenschaften haben.', intro: 'Bestimmt der Ursprung weiterhin die relevanten Teile einer Organisation, wenn unabhängig optimierte Systeme derselben Leistungsgrenze näher kommen?', outline: ['Ursprungsvariablen', 'Messung', 'Gemeinsame Herkunft', 'Negative Ergebnisse'], sections: [
    { title: 'Ursprung ist eine kontrollierte Variable', paragraphs: ['Ein Ursprungsvektor kann Ausgangsarchitektur, Trainingsdaten, Anweisungen, Werkzeuge, Vorkontext, Entwicklungsgeschichte und Zufallsstart enthalten. Frühere Entwürfe der Website nannten die Idee „Salt Sensitivity“; Preprint v0.1 ersetzt diese informelle Bezeichnung durch explizite Ursprungsvariablen und die prüfbare These Origin Attenuation.', 'Aktuelle Umgebung, Ziel, Ressourcen, zukünftige Zufälle und Messfehler werden getrennt beschrieben. Bleibt die Architektur fest, gilt das Ergebnis für eine Architekturfamilie; ist sie veränderbar, wird die Abschwächung ihres Anfangseinflusses prüfbar.'], quote: 'Origin Attenuation sagt einen sinkenden Einfluss historischer Kontingenz voraus, nicht das Verschwinden jedes Unterschieds.' },
    { title: 'Effekte statt Oberflächenähnlichkeit messen', paragraphs: ['Eine Studie muss vorab definieren, wie Eingriffe in den Ursprung ausgewählte funktionale Eigenschaften beeinflussen. Das primäre Maß kann Verteilungen verschiedener Ursprungsinterventionen vergleichen, muss aber zur behaupteten Vorhersage passen.', 'Absolute Effektstärke und ihr Anteil an der Gesamtvarianz sind verschieden. Auch die Auswahl nur erfolgreicher Systeme kann scheinbare Konvergenz erzeugen; vollständige Verläufe und gescheiterte Linien gehören deshalb in die Analyse.'] },
    { title: 'Rekonstruktion von Vererbung trennen', paragraphs: ['Ähnlichkeit kann durch Kopieren einer fertigen Lösung, gemeinsame Modellabstammung oder unabhängige Entdeckung desselben Prinzips entstehen.', 'Aussagekräftige Designs variieren Startsysteme und Entwicklungsgeschichten und erfassen gemeinsame Implementierungen, Daten und Beobachtungen als mögliche Ursachen.'] },
    { title: 'Bleibende Ursprungseffekte sind ein Ergebnis', paragraphs: ['Wenn kontrollierte Ursprungsunterschiede nahe der Grenze getrennte funktionale Ergebnisse erzeugen, wird Origin Attenuation für diese Domäne, Intervention und Beschreibungsebene geschwächt.', 'Das ist ein empirisches Ergebnis, kein gescheitertes Experiment. Unterstützung für Origin Attenuation muss zudem getrennt von funktionaler Verengung berichtet werden.'] },
  ] },
  'relational-narrowing': { ...enVisions['relational-narrowing'], category: 'IAH · Anhang C · v0.1', title: 'Relationale Verengung & starke funktionale Eindeutigkeit', description: 'Wie präziserer kausaler Kontext Alternativen unterscheiden kann und eine eindeutige funktionale Grenzklasse prüfbar wird.', intro: 'Gleiche Punktwerte bedeuten nicht zwingend gleiche Systeme: Latenz, Energie, Speicher, Zuverlässigkeit und andere vorab festgelegte Folgen können funktionale Unterschiede sichtbar machen.', outline: ['Optimalität als Relation', 'Funktionale Äquivalenz', 'Geometrie nahe der Grenze', 'Gegenbeispiele'], sections: [
    { title: 'Optimalität ist relational', paragraphs: ['Ein System ist nur relativ zu einem definierten Kontext und Ziel optimal. Genauere Messung einer bereits relevanten Folge kann Alternativen trennen, die zuvor gleich erschienen.', 'Ändert eine Verfeinerung dagegen das Bewertete, statt das ursprüngliche Kriterium genauer zu messen, entsteht ein neues Ziel und eine neue Domäne.'], quote: 'Vollständigerer Kontext kann zufällige Gleichstände verengen, garantiert aber keine Eindeutigkeit.' },
    { title: 'Punktgleichheit ist keine funktionale Äquivalenz', paragraphs: ['Funktionale Äquivalenz wird über vorab festgelegte Eigenschaften, Invarianzen und Schwellen definiert, nicht allein über den Endwert. Verschiedene Codierungen können äquivalent sein; gleich bewertete Systeme können unter Eingriffen verschieden versagen.', 'Die Beschreibungsebene zählt: Ergebnisse können konvergieren, während Algorithmen oder Architekturen verschieden bleiben.'] },
    { title: 'Geometrie nahe der Leistungsgrenze', paragraphs: ['Strong IAH verlangt, dass der funktionale Durchmesser der gesamten Menge nahezu optimaler Systeme gegen null geht und im angegebenen Raum eine gemeinsame Grenzklasse existiert.', 'Ein eindeutiges exaktes Optimum beweist nicht, dass jede Folge nahezu optimaler Systeme darauf zuläuft. Umgekehrt kann ein nicht erreichtes Supremum dennoch Konzentration nahe einem Grenzwert erlauben.'] },
    { title: 'Mehrere Lösungen können die starke These widerlegen', paragraphs: ['Symmetrien, Plateaus, Spezialisierung, Gleichgültigkeit des Ziels oder ungelöste Zielkonflikte können mehrere gleich optimale funktionale Klassen erhalten.', 'In einem endlichen oder vollständig untersuchten Raum widerlegen zwei global optimale Systeme mit positiver funktionaler Distanz eine eindeutige optimale Funktionsklasse für diese Domäne. Eine nachträglich eingeführte Präferenz beseitigt dieses Gegenbeispiel nicht.'] },
  ] },
};

export const localized = {
  en: {
    home: { status: 'Independent projects · 2026', line1: 'I build systems.', line2: 'I formulate hypotheses.', intro: 'I’m Vitalii Zhyliaiev. I build local software tools, explore intelligence and preserve a public trace of how ideas evolve.', kicker: 'Map of the space', sectionTitle: 'Practice, theory\nand context.', cards: [['01', 'Projects', 'Working products and technical experiments — from distributed computing to local-first assistants.', '/en/projects', 'acid'], ['02', 'Ideas', 'Hypotheses about intelligence, optimisation, technology and possible futures.', '/en/visions', 'blue'], ['03', 'About', 'The context behind the work and an open channel for discussion.', '/en/about', 'paper']] },
    projectHeading: { kicker: '01 / Projects', title1: 'Work', title2: 'you can open.', lead: 'Priority products and research directions, with an honest status and direct access where available.' },
    projects: enProjects,
    visionHeading: { kicker: '02 / Ideas', title1: 'Thoughts are', title2: 'prototypes too.', lead: 'The core Intelligence Attractor Hypothesis and two connected claims from the published research program.', position: 'Position', manifesto: 'This is not a collection of final answers. It is a public intellectual trail: each hypothesis has a status, boundaries and an invitation to test it.' },
    visions: enVisions,
    about: { kicker: '03 / About', name: 'Vitalii Zhyliaiev', thesis: 'building and exploring.', short: 'In short', title: 'I’m interested in systems that give people clarity and control.', paragraphs: ['I build software tools and technical experiments — from local-first Windows applications to distributed-computing concepts.', 'At the same time I explore broader questions: how intelligence optimises decisions, why independent systems may converge and where the accidents of origin give way to the constraints of reality.', 'This site connects both sides: what can already be run and what still needs to be tested.'], facts: ['Software products', 'QA & automation', 'AI & systems', 'Open hypotheses'], contact: 'Contact & feedback', contactTitle: 'Have an argument,\nan idea or a project?', email: 'Write to me', github: 'GitHub profile', discuss: 'Discuss the theories' },
  },
  de: {
    home: { status: 'Unabhängige Projekte · 2026', line1: 'Ich baue Systeme.', line2: 'Ich formuliere Hypothesen.', intro: 'Ich bin Vitalii Zhyliaiev. Ich entwickle lokale Softwarewerkzeuge, erforsche Intelligenz und dokumentiere öffentlich, wie Ideen entstehen.', kicker: 'Karte des Raums', sectionTitle: 'Praxis, Theorie\nund Kontext.', cards: [['01', 'Projekte', 'Produkte und technische Experimente — von verteiltem Rechnen bis zu Local-first-Assistenten.', '/de/projects', 'acid'], ['02', 'Ideen', 'Hypothesen über Intelligenz, Optimierung, Technologie und mögliche Zukünfte.', '/de/visions', 'blue'], ['03', 'Über mich', 'Der Kontext hinter der Arbeit und ein offener Kanal für Diskussionen.', '/de/about', 'paper']] },
    projectHeading: { kicker: '01 / Projekte', title1: 'Arbeit,', title2: 'die man öffnen kann.', lead: 'Priorisierte Produkte und Forschungsrichtungen mit ehrlichem Status und direktem Zugang, wo er verfügbar ist.' },
    projects: deProjects,
    visionHeading: { kicker: '02 / Ideen', title1: 'Gedanken sind', title2: 'auch Prototypen.', lead: 'Die zentrale Intelligence Attractor Hypothesis und zwei verbundene Thesen aus dem veröffentlichten Forschungsprogramm.', position: 'Position', manifesto: 'Dies ist keine Sammlung endgültiger Antworten, sondern eine öffentliche Denkspur: Jede Hypothese hat Status, Grenzen und eine Einladung zur Prüfung.' },
    visions: deVisions,
    about: { kicker: '03 / Über mich', name: 'Vitalii Zhyliaiev', thesis: 'entwickeln und erforschen.', short: 'Kurz gesagt', title: 'Mich interessieren Systeme, die Menschen Klarheit und Kontrolle zurückgeben.', paragraphs: ['Ich entwickle Softwarewerkzeuge und technische Experimente — von lokalen Windows-Anwendungen bis zu Konzepten für verteiltes Rechnen.', 'Parallel untersuche ich größere Fragen: Wie optimiert Intelligenz Entscheidungen, warum können unabhängige Systeme konvergieren und wo weichen Zufälle des Ursprungs den Grenzen der Realität?', 'Diese Website verbindet beide Seiten: das, was bereits funktioniert, und das, was noch geprüft werden muss.'], facts: ['Softwareprodukte', 'QA & Automatisierung', 'KI & Systeme', 'Offene Hypothesen'], contact: 'Kontakt & Feedback', contactTitle: 'Ein Argument,\neine Idee oder ein Projekt?', email: 'Schreib mir', github: 'GitHub-Profil', discuss: 'Theorien diskutieren' },
  },
};
